# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# INSTALL PLUGIN RELLOAD
unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "generic/opensuse42"

  # VM OpenSUSE
  config.vm.define "openSUSE_lpic_102_500"  do |openSUSE_lpic_102_500|

    # VARIABLE HOSTNAME
    APP_NAME= "openSUSE-lpic-102-500"

    # HOSTNAME
    openSUSE_lpic_102_500.vm.hostname = APP_NAME

    # NETWORK
    openSUSE_lpic_102_500.vm.network "public_network" ,ip: "192.168.0.136",mode: "bridge" ,bridge: [
    "ens32",
    "Marvell AQtion 5Gbit Network Adapter"
    ]

    # MOUNTS
    openSUSE_lpic_102_500.vm.synced_folder ".", "/vagrant", disabled: true
    openSUSE_lpic_102_500.vm.synced_folder "./security", "/security"
    #openSUSE_lpic_102_500.vm.synced_folder "./install", "/totvs/install", type: "rsync",rsync__args: ["-r", "--include=*"]

    # PROVIDER
    openSUSE_lpic_102_500.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name = APP_NAME
      vb.memory = 2048
      vb.cpus = 1
    end

    # PROVISION
    # SSH,FIREWALLD AND SELINUX
    openSUSE_lpic_102_500.vm.provision "shell", inline: <<-SHELL
      cat /security/id_rsa.pub >> .ssh/authorized_keys
    SHELL

    # # PACKAGES FOR PROVISION
    # openSUSE_lpic_102_500.vm.provision "shell", inline: <<-SHELL
    #   dnf install python3 -y
    # SHELL

  end

end
