# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# INSTALL PLUGIN RELLOAD
unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "gusztavvargadr/ubuntu-desktop"

  # VM ubuntu-desktop
  config.vm.define "ubuntuDesktop"  do |ubuntuDesktop|

    # VARIABLE HOSTNAME
    APP_NAME= "ubuntu-server"

    # HOSTNAME
    ubuntuDesktop.vm.hostname = APP_NAME

    # NETWORK
    ubuntuDesktop.vm.network "public_network" ,ip: "192.168.0.134",mode: "bridge" ,bridge: [
    "ens32",
    "Marvell AQtion 5Gbit Network Adapter"
    ]

    # Forward Port
    # ubuntuDesktop.vm.network "forwarded_port", guest: 8020, host: 9020, adapter: 1, guest_ip: "192.168.0.134" ,host_ip: "192.168.0.33"
    # ubuntuDesktop.vm.network "forwarded_port", guest: 2234, host: 3234, adapter: 1, guest_ip: "192.168.0.134" ,host_ip: "192.168.0.33"

    # MOUNTS
    ubuntuDesktop.vm.synced_folder ".", "/vagrant", disabled: true
    ubuntuDesktop.vm.synced_folder "./security", "/security"
    #ubuntuDesktop.vm.synced_folder "./install", "/totvs/install", type: "rsync",rsync__args: ["-r", "--include=*"]

    # PROVIDER
    ubuntuDesktop.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name = APP_NAME
      vb.memory = 2048
      vb.cpus = 1
    end

    # PROVISION
    # SSH,FIREWALLD AND SELINUX
    ubuntuDesktop.vm.provision "shell", inline: <<-SHELL
      cat /security/id_rsa.pub >> .ssh/authorized_keys
    SHELL

    # # PACKAGES FOR PROVISION
    # ubuntuDesktop.vm.provision "shell", inline: <<-SHELL
    #   dnf install python3 -y
    # SHELL

  end

end
