# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# INSTALL PLUGIN RELLOAD
unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "fedora/33-cloud-base"
  config.vm.box_version = "33.20201019.0"

  # VM srv01
  config.vm.define "srv01"  do |srv01|

    # VARIABLE HOSTNAME
    APP_NAME= "fedora-serv01"

    # HOSTNAME
    srv01.vm.hostname = APP_NAME

    # NETWORK
    srv01.vm.network "public_network" ,ip: "192.168.0.133",mode: "bridge",,bridge: [
    "ens32",
    "Marvell AQtion 5Gbit Network Adapter"
    ]

    # MOUNTS
    srv01.vm.synced_folder ".", "/vagrant", disabled: true
    srv01.vm.synced_folder "./security", "/security"

    # PROVIDER
    srv01.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name = APP_NAME
      vb.memory = 2048
      vb.cpus = 1
    end

    # PROVISION
    # SSH,FIREWALLD AND SELINUX
    srv01.vm.provision "shell", inline: <<-SHELL
      cat /security/id_rsa.pub >> .ssh/authorized_keys
    SHELL

    # # PACKAGES FOR PROVISION
    srv01.vm.provision "shell", inline: <<-SHELL
      # yum install python3 -y
      yum install  xorg-x11-server-Xorg xorg-x11-xauth xorg-x11-apps -y
    SHELL

  end

end